import { FileText, Gavel, AlertTriangle, Scale, CheckCircle } from 'lucide-react';

export default function TermsPage() {
    const currentYear = new Date().getFullYear();

    return (
        <div className="py-20 px-4 bg-slate-50 dark:bg-gray-900 min-h-screen transition-colors duration-300">
            <div className="max-w-4xl mx-auto">
                {/* Header */}
                <div className="text-center mb-16">
                    <div className="inline-flex items-center justify-center w-20 h-20 bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 rounded-3xl mb-6 shadow-sm border border-indigo-200 dark:border-indigo-800">
                        <Scale size={40} />
                    </div>
                    <h1 className="text-5xl font-extrabold text-slate-900 dark:text-white mb-6 bg-clip-text text-transparent bg-gradient-to-r from-indigo-600 to-violet-600">
                        Terms & Conditions
                    </h1>
                    <p className="text-xl text-slate-600 dark:text-gray-400 leading-relaxed font-medium">
                        Please read these terms carefully before using our platform.
                    </p>
                </div>

                <div className="space-y-8">
                    {/* Section 1: Usage */}
                    <section className="bg-white dark:bg-gray-800 p-10 rounded-[40px] shadow-xl shadow-slate-200/50 dark:shadow-none border border-slate-100 dark:border-gray-700">
                        <div className="flex items-center gap-4 mb-6">
                            <div className="bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 p-3 rounded-2xl">
                                <CheckCircle size={24} />
                            </div>
                            <h2 className="text-2xl font-bold text-slate-900 dark:text-white">1. Acceptance of Terms</h2>
                        </div>
                        <p className="text-slate-600 dark:text-gray-400 leading-relaxed">
                            By accessing AI Form-to-App Builder, you agree to be bound by these terms. Our service allows you to generate CRUD applications dynamically. You are responsible for the legality and accuracy of the data models you define.
                        </p>
                    </section>

                    {/* Section 2: Account Responsibility */}
                    <section className="bg-white dark:bg-gray-800 p-10 rounded-[40px] shadow-xl shadow-slate-200/50 dark:shadow-none border border-slate-100 dark:border-gray-700">
                        <div className="flex items-center gap-4 mb-6">
                            <div className="bg-violet-100 dark:bg-violet-900/30 text-violet-600 dark:text-violet-400 p-3 rounded-2xl">
                                <FileText size={24} />
                            </div>
                            <h2 className="text-2xl font-bold text-slate-900 dark:text-white">2. Account Responsibility</h2>
                        </div>
                        <p className="text-slate-600 dark:text-gray-400 leading-relaxed mb-4">
                            You are responsible for maintaining the confidentiality of your login credentials. Any activity occurring under your account is your sole responsibility.
                        </p>
                        <div className="bg-violet-50 dark:bg-violet-900/20 p-4 rounded-2xl border border-violet-100 dark:border-violet-800 text-violet-800 dark:text-violet-400 text-sm font-medium italic">
                            "Build responsibly. Do not use this tool for generating applications that violate any local or international laws."
                        </div>
                    </section>

                    {/* Section 3: Disclaimer */}
                    <section className="bg-white dark:bg-gray-800 p-10 rounded-[40px] shadow-xl shadow-slate-200/50 dark:shadow-none border border-slate-100 dark:border-gray-700">
                        <div className="flex items-center gap-4 mb-6">
                            <div className="bg-red-100 dark:bg-red-900/30 text-red-600 dark:text-red-400 p-3 rounded-2xl">
                                <AlertTriangle size={24} />
                            </div>
                            <h2 className="text-2xl font-bold text-slate-900 dark:text-white">3. Generation Disclaimer</h2>
                        </div>
                        <p className="text-slate-600 dark:text-gray-400 leading-relaxed mb-4">
                            The applications generated by our builder are provided "as-is". While we aim for high reliability and security, <strong>Roonjha Developer</strong> does not guarantee 100% uptime or error-free operation of the generated code.
                        </p>
                        <p className="text-slate-600 dark:text-gray-400 leading-relaxed font-bold">
                            We are not responsible for any data loss occurring within your generated applications.
                        </p>
                    </section>

                    {/* Section 4: Rights */}
                    <section className="bg-white dark:bg-gray-800 p-10 rounded-[40px] shadow-xl shadow-slate-200/50 dark:shadow-none border border-slate-100 dark:border-gray-700">
                        <div className="flex items-center gap-4 mb-6">
                            <div className="bg-amber-100 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400 p-3 rounded-2xl">
                                <Gavel size={24} />
                            </div>
                            <h2 className="text-2xl font-bold text-slate-900 dark:text-white">4. Modifications to Service</h2>
                        </div>
                        <p className="text-slate-600 dark:text-gray-400 leading-relaxed">
                            We reserve the right to modify or discontinue the service at any time. We also reserve the right to update these terms. Continued use of the platform after updates implies acceptance of the new terms.
                        </p>
                    </section>

                    {/* Bottom attribution */}
                    <div className="text-center pt-8 border-t border-slate-200 dark:border-gray-700">
                        <p className="text-slate-400 dark:text-gray-500 text-xs font-bold uppercase tracking-widest leading-loose">
                            © {currentYear} Roonjha Developer. All rights reserved.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}
